import type { Metadata } from "next";
import { Inter, Space_Grotesk, Space_Mono } from "next/font/google";

import { QueryProvider } from "@/providers/QueryProvider";
import { AuthProvider } from "@/features/auth/context";
import { ThemeProvider } from "@/shared/theme";
import { ThemeInitScript } from "@/shared/theme/theme-init-script";
import "./globals.css";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });
const spaceGrotesk = Space_Grotesk({ variable: "--font-space-grotesk", subsets: ["latin"] });
const spaceMono = Space_Mono({ variable: "--font-space-mono", weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" data-js-focus-visible="" className="h-full antialiased" suppressHydrationWarning>
      <body className={`${inter.variable} ${spaceGrotesk.variable} ${spaceMono.variable} min-h-full flex flex-col`}>
        <ThemeInitScript />
        <QueryProvider>
          <ThemeProvider>
            <AuthProvider>{children}</AuthProvider>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
